apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Service
    metadata:
      name: ${NAME}
    spec:
      ports:
        - port: 8080
          targetPort: 8080
      selector:
        deploymentconfig: ${NAME}
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: ${NAME}
    spec:
      replicas: 1
      selector:
        deploymentconfig: ${NAME}
      template:
        metadata:
          labels:
            deploymentconfig: ${NAME}
        spec:
          containers:
            - image: '192.168.33.11/openshift/jenkins-spring-build:latest'
              name: ${NAME}
              ports:
                - containerPort: 8080
                  protocol: TCP

  - apiVersion: v1
    kind: Route
    metadata:
      name: ${NAME}
    spec:
      to:
        kind: Service
        name: ${NAME}
parameters:
  - description: The name assigned to all of the frontend objects defined in this project.
    displayName: Name
    name: NAME
    required: true
    value: jenkins-spring-build