apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Service
    metadata:
      name: jenkins-spring-build
    spec:
      ports:
        - port: 8080
          targetPort: 8080
      selector:
        deploymentconfig: jenkins-spring-build
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: jenkins-spring-build
    spec:
      replicas: 1
      selector:
        deploymentconfig: jenkins-spring-build
      template:
        metadata:
          labels:
            deploymentconfig: jenkins-spring-build
        spec:
          containers:
            - image: '81.169.198.21:33354/jenkins/jenkins-spring-build'
              name: jenkins-spring-build
              ports:
                - containerPort: 8080
                  protocol: TCP

  - apiVersion: v1
    kind: Route
    metadata:
      name: jenkins-spring-build
    spec:
      to:
        kind: Service
        name: jenkins-spring-build
